# -*- coding: utf-8 -*-
"""HRMedicine prescription.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyEazgxevl4M0YRsBBVvJgm99CtFIQe4
"""

!pip install -q gradio requests huggingface-hub transformers

# Single-cell implementation for "AI medical prescription verification app"
# - Uses Gradio for UI
# - Uses RxNav (RxNorm) APIs for drug lookups and interaction checks (no API key)
# - Optionally uses Hugging Face Inference API with model "ibm/granite-3.3-2b-instruct" if HF_TOKEN is provided
# - Includes robust fallbacks so the cell runs without errors even if HF_TOKEN is not set.


import os
import re
import json
import time
import requests
import traceback
from typing import List, Dict, Tuple, Optional
import gradio as gr

# ---------------------------
# Configuration & Constants
# ---------------------------
HF_TOKEN = os.environ.get("HF_TOKEN", None)  # Set in Colab if you want HF inference
HF_MODEL_ID = "ibm/granite-3.3-2b-instruct"  # As requested
RXNAV_BASE = "https://rxnav.nlm.nih.gov/REST"

# Some small example dosage ranges for a few common drugs (used for basic dosage checking fallback).
# This is illustrative — for production you must use authoritative dosage databases and clinical logic.
EXAMPLE_DOSAGE_RANGES = {
    "ibuprofen": {"unit": "mg", "min": 200, "max": 800, "freq_note": "q4-6h PRN"},
    "paracetamol": {"unit": "mg", "min": 325, "max": 1000, "freq_note": "q4-6h PRN"},
    "amoxicillin": {"unit": "mg", "min": 250, "max": 500, "freq_note": "TID"},
    "metformin": {"unit": "mg", "min": 500, "max": 2000, "freq_note": "daily total"},
}

# ---------------------------
# Utility functions
# ---------------------------

def safe_json(response):
    try:
        return response.json()
    except Exception:
        return {}

# 1) RxNorm search to get RxCUI and names
def rxnorm_search(drug_name: str) -> Dict:
    url = f"{RXNAV_BASE}/rxcui.json"
    params = {"name": drug_name}
    try:
        resp = requests.get(url, params=params, timeout=10)
        data = safe_json(resp)
        rxcui = data.get("idGroup", {}).get("rxnormId", [])
        if rxcui:
            rxcui = rxcui[0]
            # get properties
            prop = requests.get(f"{RXNAV_BASE}/rxcui/{rxcui}/properties.json", timeout=10).json()
            return {"rxcui": rxcui, "properties": prop.get("properties", {})}
        else:
            # try approximate search
            resp2 = requests.get(f"{RXNAV_BASE}/approximateTerm.json", params={"term": drug_name}, timeout=10)
            data2 = safe_json(resp2)
            candidates = data2.get("approximateGroup", {}).get("candidate", [])
            return {"rxcui": None, "candidates": candidates}
    except Exception as e:
        return {"error": str(e)}

# 2) Get interactions via RxNav interaction API
def rxnav_interactions(rxcuis: List[str]) -> List[Dict]:
    # Accepts list of RxCUIs, returns interactions if any
    results = []
    if not rxcuis:
        return results
    try:
        rxcui_param = "+".join(rxcuis)
        url = f"{RXNAV_BASE}/interaction/list.json"
        params = {"rxcuis": rxcui_param}
        resp = requests.get(url, params=params, timeout=15)
        data = safe_json(resp)
        interaction_group = data.get("interactionTypeGroup", [])
        for group in interaction_group:
            for itype in group.get("interactionType", []):
                for interaction in itype.get("interactionPair", []):
                    results.append({
                        "interactionConcept": interaction.get("interactionConcept", []),
                        "description": interaction.get("description"),
                        "severity": interaction.get("severity"),
                        "contraindication": interaction.get("contraindication"),
                    })
    except Exception as e:
        results.append({"error": str(e)})
    return results

# 3) Get drug label info (openFDA or RxNav concept) - we keep it simple using RxNav properties
def get_drug_details_by_rxcui(rxcui: str) -> Dict:
    try:
        resp = requests.get(f"{RXNAV_BASE}/rxcui/{rxcui}/allProperties.json", params={"prop": "all"}, timeout=10)
        return safe_json(resp)
    except Exception as e:
        return {"error": str(e)}

# 4) Simple dosage parser (extract number and unit)
def parse_dosage(dosage_text: str) -> Tuple[Optional[float], Optional[str]]:
    if not dosage_text:
        return None, None
    m = re.search(r'([0-9]+(?:\.[0-9]+)?)\s*(mg|g|mcg|μg|ml|units)?', dosage_text, re.I)
    if m:
        val = float(m.group(1))
        unit = m.group(2).lower() if m.group(2) else None
        # normalize microgram
        if unit == "μg":
            unit = "mcg"
        return val, unit
    return None, None

# 5) Simple dosage check against example ranges
def check_dosage_range(drug_name: str, dose_val: Optional[float], dose_unit: Optional[str]) -> str:
    if not dose_val:
        return "No dosage provided to check."
    dn = drug_name.lower()
    # try to find simple match
    for k in EXAMPLE_DOSAGE_RANGES:
        if k in dn or dn in k:
            info = EXAMPLE_DOSAGE_RANGES[k]
            expected_unit = info["unit"]
            if dose_unit and dose_unit != expected_unit:
                return f"Unit mismatch: provided {dose_unit}, expected {expected_unit} for {k} (approx)."
            if dose_val < info["min"]:
                return f"Dosage {dose_val}{expected_unit} is below typical lower bound ({info['min']}{expected_unit}) for {k}."
            if dose_val > info["max"]:
                return f"Dosage {dose_val}{expected_unit} is above typical upper bound ({info['max']}{expected_unit}) for {k}."
            return f"Dosage {dose_val}{expected_unit} is within example range ({info['min']}-{info['max']}{expected_unit})."
    return "No local dosage ranges found for this medication (use authoritative clinical database in production)."

# 6) Allergy check - rudimentary: check given allergy keywords against drug name and known synonyms (from RxNav properties)
def allergy_check(allergies: List[str], drug_names: List[str]) -> List[str]:
    alerts = []
    lower_drugs = " ".join(drug_names).lower()
    for a in allergies:
        if not a:
            continue
        if a.lower() in lower_drugs:
            alerts.append(f"Allergy match: patient allergic to '{a}', appears in medication list.")
    return alerts

# 7) Basic prescriber license validators (format checks)
def validate_license_format(license_text: str) -> Tuple[bool, str]:
    if not license_text:
        return False, "No license number provided."
    # Very permissive check: between 4 and 20 alnum chars
    if re.match(r'^[A-Za-z0-9\-\s]{4,20}$', license_text):
        return True, "Format looks OK (not authoritative)."
    return False, "License number format looks invalid."

# 8) DEA number validation (US DEA number checksum algorithm)
def validate_dea_number(dea: str) -> Tuple[bool, str]:
    if not dea:
        return False, "No DEA number provided."
    dea = dea.replace('-', '').upper()
    if len(dea) != 9:
        return False, "DEA must be 9 characters (e.g., AB1234563)."
    if not re.match(r'^[A-Z][A-Z]\d{7}$', dea):
        return False, "DEA format invalid (expected 2 letters followed by 7 digits)."
    try:
        digits = dea[2:]
        # checksum algorithm:
        # 1) Sum of 1st,3rd,5th digits
        # 2) Sum of 2nd,4th,6th digits *2
        # 3) Add together and last digit should equal 7th digit (check digit)
        nums = [int(d) for d in digits]
        s1 = nums[0] + nums[2] + nums[4]
        s2 = (nums[1] + nums[3] + nums[5]) * 2
        check = (s1 + s2) % 10
        if check == nums[6]:
            return True, "DEA number appears valid (checksum OK)."
        else:
            return False, "DEA checksum failed."
    except Exception as e:
        return False, f"DEA validation error: {e}"

# ---------------------------
# Optional: Hugging Face inference wrapper
# ---------------------------
def hf_generate(prompt: str, max_length=512, temperature=0.0) -> Tuple[bool, str]:
    """
    Attempt to call Hugging Face Inference API with HF_TOKEN and model HF_MODEL_ID.
    Returns (used_hf:boolean, output_text).
    If HF_TOKEN not set or call fails, returns (False, message).
    """
    if not HF_TOKEN:
        return False, "HF_TOKEN not set; using fallback parsing."
    try:
        from huggingface_hub import InferenceApi
        inference = InferenceApi(repo_id=HF_MODEL_ID, token=HF_TOKEN)
        # For instruction style models, sending prompt as input
        resp = inference(prompt, params={"max_new_tokens": 512, "temperature": temperature})
        # inference may return dict or string
        if isinstance(resp, dict) and 'generated_text' in resp:
            return True, resp['generated_text']
        if isinstance(resp, str):
            return True, resp
        # otherwise try to serialize
        return True, str(resp)
    except Exception as e:
        return False, f"Hugging Face inference failed: {e}"

# ---------------------------
# NLP Extraction: either use HF model or fallback rules
# ---------------------------
def extract_prescription_structured(prescription_text: str) -> Dict:
    """
    Attempts to extract: patient name, DOB, MRN, prescriber name, DEA/license, list of medications with dosage.
    Uses HF model if available; otherwise uses regex-based fallback.
    """
    # Try HF model first
    prompt = (
        "You are a medical-prescription parser. Extract structured fields from the given prescription text.\n\n"
        "Fields to extract as JSON:\n"
        "patient_name, dob (YYYY-MM-DD if possible), medical_record_number, prescriber_name, prescriber_license, prescriber_dea, medications: [ {name, dose_text, frequency, route} ]\n\n"
        "Prescription text:\n\"\"\"\n" + prescription_text + "\n\"\"\"\n\nReturn ONLY valid JSON."
    )
    used_hf, out = hf_generate(prompt)
    if used_hf:
        # try to parse JSON in output
        try:
            # some models may preface with explanation, so find first '{'
            start = out.find('{')
            if start != -1:
                candidate = out[start:]
                data = json.loads(candidate)
                return {"source": "hf", "data": data}
        except Exception:
            # fall through to fallback parsing
            pass

    # Fallback deterministic parsing
    data = {
        "patient_name": None,
        "dob": None,
        "medical_record_number": None,
        "prescriber_name": None,
        "prescriber_license": None,
        "prescriber_dea": None,
        "medications": []
    }
    text = prescription_text

    # Simple heuristics
    # patient name: look for "Patient:" or "Name:" lines
    m = re.search(r'Patient[:\-]?\s*([A-Za-z\s.-]+?)(?:, DOB|, *MRN|\n|$)', text, re.I)
    if m:
        data["patient_name"] = m.group(1).strip()

    # DOB
    m = re.search(r'DOB[:\-]?\s*(\d{4}-\d{2}-\d{2}|\d{1,2}[/\-]\d{1,2}[/\-]\d{2,4})', text, re.I)
    if m:
        data["dob"] = m.group(1)

    # MRN / medical record
    m = re.search(r'(MRN|Medical Record #|Record #)[:\-]?\s*([A-Za-z0-9\-]+)', text, re.I)
    if m:
        data["medical_record_number"] = m.group(2)

    # Prescriber name / license / DEA
    m = re.search(r'(?:Prescriber|Provider|Dr\.|Physician)[:\-]?\s*([A-Za-z\s.-]+?)(?:, License|, *DEA|\n|$)', text, re.I)
    if m:
        data["prescriber_name"] = m.group(1).strip()
    m = re.search(r'(License|Lic#|License #)[:\-]?\s*([A-Za-z0-9\-]+)', text, re.I)
    if m:
        data["prescriber_license"] = m.group(2).strip()
    m = re.search(r'(DEA[:\-]?\s*|DEA #[:\-]?\s*)([A-Za-z0-9\-]+)', text, re.I)
    if m:
        data["prescriber_dea"] = m.group(2).strip()

    # Extract medication lines (rudimentary: lines starting with drug name or bullet)
    meds = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        # a med line often contains mg, tablet, cap, qd, BID, etc.
        if re.search(r'\b(mg|tablet|tab|cap|capsule|ml|mcg|puffs|spray|drop|qd|bid|tid|q\d+h)\b', line, re.I):
            # try to split to name and rest
            parts = re.split(r'[\-–—:]', line, maxsplit=1)
            if len(parts) == 2:
                name_part, rest = parts[0].strip(), parts[1].strip()
            else:
                # use first few words as name heuristics
                toks = line.split()
                name_part = " ".join(toks[:2])
                rest = " ".join(toks[2:])
            # Clean medication name by removing leading numbers (e.g., '1. Ibuprofen')
            name_part = re.sub(r'^\d+\.\s*', '', name_part).strip()
            # extract dosage text
            dose_match = re.search(r'([0-9]+(?:\.[0-9]+)?\s*(?:mg|g|mcg|μg|ml|units))', line, re.I)
            dose_text = dose_match.group(1) if dose_match else ""
            meds.append({"name": name_part, "dose_text": dose_text, "raw": line})
    data["medications"] = meds
    return {"source": "fallback", "data": data}

# ---------------------------
# Core verifier pipeline
# ---------------------------
def verify_prescription(presc_text: str, current_medications_text: str, allergies_text: str,
                        patient_name: str, patient_dob: str, patient_mrn: str,
                        prescriber_name: str, prescriber_license: str, prescriber_dea: str) -> Dict:
    """
    Main orchestration function that returns a structured verification report.
    """
    try:
        # 1) Extract fields from free-form prescription if provided
        extracted = extract_prescription_structured(presc_text)
        # Use explicit fields if provided (prefer explicit over extracted)
        # Build medication list from extraction + current_medications_text
        meds = []
        if extracted.get("data", {}).get("medications"):
            meds.extend(extracted["data"]["medications"])
        # Also parse current_medications_text lines
        for line in current_medications_text.splitlines():
            line = line.strip()
            if not line:
                continue
            # basic parse: first token(s) as name
            dose = ""
            m = re.search(r'([0-9]+(?:\.[0-9]+)?\s*(?:mg|g|mcg|ml|units))', line, re.I)
            if m:
                dose = m.group(1)
            meds.append({"name": line.split()[0:2] and " ".join(line.split()[:2]) or line, "dose_text": dose, "raw": line})

        med_names = [m.get("name","").strip() for m in meds if m.get("name")]
        # 2) Drug validation via RxNav
        drug_validations = []
        rxcuis = []
        for m in meds:
            name = m.get("name", "")
            if not name:
                continue
            rx = rxnorm_search(name)
            if rx.get("rxcui"):
                rxcui = rx["rxcui"]
                rxcuis.append(rxcui)
                props = rx.get("properties", {})
                brand = props.get("brandName") or props.get("synonym") or props.get("name")
                generic = props.get("genericName") or props.get("name")
                drug_validations.append({
                    "input_name": name,
                    "found_rxcui": rxcui,
                    "brand": brand,
                    "generic": generic,
                    "rxnav_properties": props
                })
            else:
                drug_validations.append({"input_name": name, "found_rxcui": None, "candidates": rx.get("candidates", [])})

        # 3) Dosage checks (simple)
        dosage_checks = []
        for m in meds:
            name = m.get("name", "")
            dv, du = parse_dosage(m.get("dose_text", ""))
            dosage_checks.append({
                "med_name": name,
                "dose_text": m.get("dose_text"),
                "parsed_value": dv,
                "parsed_unit": du,
                "dosage_check_result": check_dosage_range(name, dv, du)
            })

        # 4) Interaction checks via rxcuis
        interactions = rxnav_interactions(list(set([r for r in rxcuis if r])))
        # 5) Allergy checks
        allergies = [a.strip() for a in allergies_text.split(",") if a.strip()]
        allergy_alerts = allergy_check(allergies, med_names)

        # 6) Prescription completeness and prescriber checks
        completeness = {}
        completeness["patient_name_ok"] = bool(patient_name or extracted.get("data",{}).get("patient_name"))
        completeness["dob_ok"] = bool(patient_dob or extracted.get("data",{}).get("dob"))
        completeness["mrn_ok"] = bool(patient_mrn or extracted.get("data",{}).get("medical_record_number"))
        completeness["prescriber_name_ok"] = bool(prescriber_name or extracted.get("data",{}).get("prescriber_name"))
        lic_ok, lic_msg = validate_license_format(prescriber_license or extracted.get("data",{}).get("prescriber_license",""))
        dea_ok, dea_msg = validate_dea_number(prescriber_dea or extracted.get("data",{}).get("prescriber_dea",""))
        completeness["prescriber_license_ok"] = lic_ok
        completeness["prescriber_license_msg"] = lic_msg
        completeness["prescriber_dea_ok"] = dea_ok
        completeness["prescriber_dea_msg"] = dea_msg

        # 7) Medicine verification summary (cross-checks)
        med_summary = []
        for dv in drug_validations:
            r = {"input_name": dv.get("input_name")}
            if dv.get("found_rxcui"):
                r["verified"] = True
                r["rxcui"] = dv.get("found_rxcui")
                r["brand"] = dv.get("brand")
                r["generic"] = dv.get("generic")
            else:
                r["verified"] = False
                r["candidates"] = dv.get("candidates", [])
            med_summary.append(r)

        # Build final report
        report = {
            "extraction_source": extracted.get("source"),
            "extracted_data": extracted.get("data"),
            "medication_validations": med_summary,
            "dosage_checks": dosage_checks,
            "interactions_found": interactions,
            "allergy_alerts": allergy_alerts,
            "completeness": completeness,
        }

        return {"success": True, "report": report}
    except Exception as e:
        return {"success": False, "error": str(e), "trace": traceback.format_exc()}

# ---------------------------
# Gradio UI
# ---------------------------
with gr.Blocks() as demo:
    gr.Markdown("## AI Medical Prescription Verification (Colab demo)\n\n"
                "Paste a prescription (or free text) and provide current meds/allergies. "
                "Optional: set HF_TOKEN in environment to enable the requested Hugging Face model for parsing.")
    with gr.Row():
        with gr.Column(scale=2):
            presc_input = gr.Textbox(label="Prescription text (free-form)", lines=8, placeholder="Paste prescription text here...")
            current_meds = gr.Textbox(label="Patient's current medications (one per line)", lines=4, placeholder="e.g., Metformin 500 mg BID")
            allergies = gr.Textbox(label="Allergies (comma-separated)", lines=2, placeholder="e.g., Penicillin, Sulfa")
        with gr.Column(scale=1):
            patient_name = gr.Textbox(label="Patient name (optional)")
            patient_dob = gr.Textbox(label="Patient DOB (optional)")
            patient_mrn = gr.Textbox(label="Patient MRN (optional)")
            prescriber_name = gr.Textbox(label="Prescriber name (optional)")
            prescriber_license = gr.Textbox(label="Prescriber license (optional)")
            prescriber_dea = gr.Textbox(label="Prescriber DEA (optional)")
    run_btn = gr.Button("Verify prescription")
    output = gr.JSON(label="Verification report (JSON)")

    def run_verification(presc_text, current_meds_text, allergies_text,
                         p_name, p_dob, p_mrn, pr_name, pr_license, pr_dea):
        payload = verify_prescription(
            presc_text or "", current_meds_text or "", allergies_text or "",
            p_name or "", p_dob or "", p_mrn or "",
            pr_name or "", pr_license or "", pr_dea or ""
        )
        return payload

    run_btn.click(run_verification, inputs=[presc_input, current_meds, allergies,
                                           patient_name, patient_dob, patient_mrn,
                                           prescriber_name, prescriber_license, prescriber_dea],
                  outputs=output)

# Launch Gradio (in Colab, set share=True if you want external link)
demo.launch(share=True, debug=True)

sample_presc_text = """
Patient: Jane Doe, DOB: 1985-03-15, MRN: JD12345
Prescriber: Dr. Alex Smith, License#: 123456, DEA: AB1234567

Medications:
1. Ibuprofen 400 mg q6h PRN pain
2. Amoxicillin 250mg TID for 7 days
"""

sample_current_meds = """
Metformin 500 mg BID
"""

sample_allergies = "Penicillin, Aspirin"

sample_patient_name = ""
sample_patient_dob = ""
sample_patient_mrn = ""
sample_prescriber_name = ""
sample_prescriber_license = ""
sample_prescriber_dea = ""


report = verify_prescription(
    presc_text=sample_presc_text,
    current_medications_text=sample_current_meds,
    allergies_text=sample_allergies,
    patient_name=sample_patient_name,
    patient_dob=sample_patient_dob,
    patient_mrn=sample_patient_mrn,
    prescriber_name=sample_prescriber_name,
    prescriber_license=sample_prescriber_license,
    prescriber_dea=sample_prescriber_dea
)

print(json.dumps(report, indent=2))

sample_presc_text = """
Patient: Jane Doe, DOB: 1985-03-15, MRN: JD12345
Prescriber: Dr. Alex Smith, License#: 123456, DEA: AB1234567

Medications:
1. Ibuprofen 400 mg q6h PRN pain
2. Amoxicillin 250mg TID for 7 days
"""

sample_current_meds = """
Metformin 500 mg BID
"""

sample_allergies = "Penicillin, Aspirin"

sample_patient_name = ""
sample_patient_dob = ""
sample_patient_mrn = ""
sample_prescriber_name = ""
sample_prescriber_license = ""
sample_prescriber_dea = ""


report = verify_prescription(
    presc_text=sample_presc_text,
    current_medications_text=sample_current_meds,
    allergies_text=sample_allergies,
    patient_name=sample_patient_name,
    patient_dob=sample_patient_dob,
    patient_mrn=sample_patient_mrn,
    prescriber_name=sample_prescriber_name,
    prescriber_license=sample_prescriber_license,
    prescriber_dea=sample_prescriber_dea
)

print(json.dumps(report, indent=2))